[profile.default]
src = "contract"
out = "out"
libs = ["lib"]

fs_permissions = [{ access = "read", path = "./proofs"}]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config